### ISSUE TITLE
config.yaml autoconnect_delay ignored

### ISSUE THREAD

**Issue by jshank** [markwal/OctoPrint-PortLister#4]
My Wanhao Duplicator i3 takes a bit longer to connect to after waking up. I set the delay to 40 seconds but it still tries to connect at 20 seconds and hangs on connect forever.

```
plugins:
  PortLister:
    autoconnect_delay: 40
  announcements:
    channels:
      _important:
        read_until: 1460575175
```
